Config = {

    EnableJobLock = true, -- Set to false to disable job/grade restrictions

    AllowedJobs = { -- Job name as key, minimum grade as value
        ['admin'] = 4,
        ['staff'] = 4,
		['police'] = 4,
        -- Add more jobs as needed, e.g., ['police'] = 4,
    },
	
    -- Interaction Config
    Command = 'itemspawner', -- Command to open the item spawner
    UIStyle = 'style1', -- Default UI style: style1, style2, style3, style4, style5

    -- UI Styles
    UIStyles = {
        style1 = { -- Dark Modern Glass
            primaryBg = 'rgba(32, 33, 36, 0.8)',
            secondaryBg = 'rgba(48, 49, 52, 0.7)',
            accent = '#8ab4f8',
            textPrimary = '#e8eaed',
            textSecondary = '#9aa0a6',
            borderColor = 'rgba(95, 99, 104, 0.5)',
            blur = '10px',
        },
        style2 = { -- Light Clean Glass
            primaryBg = 'rgba(245, 245, 245, 0.8)',
            secondaryBg = 'rgba(255, 255, 255, 0.7)',
            accent = '#4caf50',
            textPrimary = '#212121',
            textSecondary = '#757575',
            borderColor = 'rgba(224, 224, 224, 0.5)',
            blur = '12px',
        },
        style3 = { -- Neon Night Glass
            primaryBg = 'rgba(26, 26, 46, 0.8)',
            secondaryBg = 'rgba(22, 36, 71, 0.7)',
            accent = '#ff2e63',
            textPrimary = '#ffffff',
            textSecondary = '#cccccc',
            borderColor = 'rgba(255, 46, 99, 0.5)',
            blur = '8px',
        },
        style4 = { -- Retro Glass
            primaryBg = 'rgba(46, 46, 46, 0.8)',
            secondaryBg = 'rgba(74, 74, 74, 0.7)',
            accent = '#ffca28',
            textPrimary = '#ffffff',
            textSecondary = '#bdbdbd',
            borderColor = 'rgba(117, 117, 117, 0.5)',
            blur = '10px',
        },
        style5 = { -- Oceanic Glass
            primaryBg = 'rgba(0, 48, 135, 0.8)',
            secondaryBg = 'rgba(0, 74, 173, 0.7)',
            accent = '#00e5ff',
            textPrimary = '#ffffff',
            textSecondary = '#b3e5fc',
            borderColor = 'rgba(2, 136, 209, 0.5)',
            blur = '10px',
        },
    },

    -- Item Mapping
    Products = {
    ['normal'] = {
        { name = 'tosti',              price = 0, amount = 5000 },
        { name = 'water_bottle',       price = 0, amount = 5000 },
        { name = 'kurkakola',          price = 0, amount = 5000 },
        { name = 'twerks_candy',       price = 0, amount = 5000 },
        { name = 'snikkel_candy',      price = 0, amount = 5000 },
        { name = 'sandwich',           price = 0, amount = 5000 },
        { name = 'beer',               price = 0, amount = 5000 },
        { name = 'whiskey',            price = 0, amount = 5000 },
        { name = 'vodka',              price = 0, amount = 5000 },
        { name = 'bandage',            price = 0, amount = 5000 },
        { name = 'lighter',            price = 0, amount = 5000 },
        { name = 'paper',              price = 0, amount = 5000 },
        { name = 'coffee',             price = 0, amount = 5000 },
    },
    ['liquor'] = {
        { name = 'beer',               price = 0, amount = 5000 },
        { name = 'whiskey',            price = 0, amount = 5000 },
        { name = 'vodka',              price = 0, amount = 5000 },
    },
	['drugs'] = {
        { name = 'cocaine', price = 0, amount = 5000 },
        { name = 'weed', price = 0, amount = 5000 },
        { name = 'weed_lemonhaze', price = 0, amount = 5000 },
        { name = 'weed_white_widow', price = 0, amount = 5000 },
        { name = 'weed_purple_haze', price = 0, amount = 5000 },
        { name = 'weed_blueberry', price = 0, amount = 5000 },
        { name = 'weed_og', price = 0, amount = 5000 },
        { name = 'crack_baggy', price = 0, amount = 5000 },
        { name = 'xtcbaggy', price = 0, amount = 5000 },
        { name = 'oxy', price = 0, amount = 5000 },
        { name = 'meth', price = 0, amount = 5000 },
        { name = 'bag_blueberry_haze', price = 0, amount = 5000 },
        { name = 'bag_lemonhaze', price = 0, amount = 5000 },
        { name = 'bag_og_kush', price = 0, amount = 5000 },
        { name = 'bag_purple_haze', price = 0, amount = 5000 },
        { name = 'bag_white_widow', price = 0, amount = 5000 },
        { name = 'bag_base', price = 0, amount = 5000 },
        { name = 'bag_fent', price = 0, amount = 5000 },
        { name = 'bag_pcp', price = 0, amount = 5000 },
        { name = 'bag_heroin', price = 0, amount = 5000 },
        { name = 'bag_mcat', price = 0, amount = 5000 },
        { name = 'bag_spice', price = 0, amount = 5000 },
        { name = 'adderall', price = 0, amount = 5000 },
        { name = 'benzos', price = 0, amount = 5000 },
        { name = 'magic_mushroom', price = 0, amount = 5000 },
        { name = 'bag_mdma', price = 0, amount = 5000 },
        { name = 'bag_ketamine', price = 0, amount = 5000 },
        { name = 'bag_kalvin', price = 0, amount = 5000 },
        { name = 'pressed_mdma_pill', price = 0, amount = 5000 },
        { name = 'acid_tab', price = 0, amount = 5000 },
        { name = 'acid_blue_typhoon', price = 0, amount = 5000 },
        { name = 'acid_blue_typhoon_icelolly', price = 0, amount = 5000 },
        { name = 'weed_cookie', price = 0, amount = 5000 },
        { name = 'weed_strawberry_milkshake', price = 0, amount = 5000 },
        { name = 'weed_chocolate_milkshake', price = 0, amount = 5000 },
        { name = 'weed_donut', price = 0, amount = 5000 },
        { name = 'weed_glazed_donuts', price = 0, amount = 5000 },
        { name = 'weed_bread', price = 0, amount = 5000 },
        { name = 'weed_strawberry_shortcake', price = 0, amount = 5000 },
        { name = 'weed_penut_butter_cup', price = 0, amount = 5000 },
        { name = 'weed_passionfruit_cheesecake', price = 0, amount = 5000 },
        { name = 'weed_chocolate_brownie', price = 0, amount = 5000 },
        { name = 'weed_pretzel', price = 0, amount = 5000 },
        { name = 'weed_gummi_bears', price = 0, amount = 5000 },
        { name = 'weed_lollypop', price = 0, amount = 5000 },
    },
	['drug crafting'] = {
        { name = 'oven', price = 0, amount = 5000 },
        { name = 'weed_processing_table', price = 0, amount = 5000 },
        { name = 'cocaine_processing_table', price = 0, amount = 5000 },
        { name = 'mdma_processing_table', price = 0, amount = 5000 },
        { name = 'acid_processing_table', price = 0, amount = 5000 },
    },
    ['hardware'] = {
        { name = 'lockpick',           price = 0, amount = 5000 },
        { name = 'weapon_wrench',      price = 0, amount = 5000 },
        { name = 'weapon_hammer',      price = 0, amount = 5000 },
        { name = 'repairkit',          price = 0, amount = 5000 },
        { name = 'screwdriverset',     price = 0, amount = 5000 },
        { name = 'phone',              price = 0, amount = 5000 },
        { name = 'radio',              price = 0, amount = 5000 },
        { name = 'binoculars',         price = 0, amount = 5000 },
        { name = 'firework1',          price = 0, amount = 5000 },
        { name = 'firework2',          price = 0, amount = 5000 },
        { name = 'firework3',          price = 0, amount = 5000 },
        { name = 'firework4',          price = 0, amount = 5000 },
        { name = 'fitbit',             price = 0, amount = 5000 },
        { name = 'cleaningkit',        price = 0, amount = 5000 },
        { name = 'advancedrepairkit',  price = 0, amount = 5000 },
    },
    ['weapons'] = {
        { name = 'weapon_knife',       price = 0, amount = 5000 },
        { name = 'weapon_bat',         price = 0, amount = 5000 },
        { name = 'weapon_hatchet',     price = 0, amount = 5000 },        
        { name = 'weapon_pistol',      price = 0, amount = 5000 },
        { name = 'weapon_snspistol',   price = 0, amount = 5000 },
        { name = 'weapon_vintagepistol', price = 0, amount = 5000 },
        { name = 'weapon_dagger',      price = 0, amount = 5000 },
        { name = 'weapon_bottle',      price = 0, amount = 5000 },
        { name = 'weapon_crowbar',     price = 0, amount = 5000 },
        { name = 'weapon_flashlight',  price = 0, amount = 5000 },
        { name = 'weapon_golfclub',    price = 0, amount = 5000 },
        { name = 'weapon_knuckle',     price = 0, amount = 5000 },
        { name = 'weapon_machete',     price = 0, amount = 5000 },
        { name = 'weapon_switchblade', price = 0, amount = 5000 },
        { name = 'weapon_nightstick',  price = 0, amount = 5000 },
        { name = 'weapon_battleaxe',   price = 0, amount = 5000 },
        { name = 'weapon_briefcase',   price = 0, amount = 5000 },
        { name = 'weapon_briefcase_02', price = 0, amount = 5000 },
        { name = 'weapon_garbagebag',  price = 0, amount = 5000 },
        { name = 'weapon_handcuffs',   price = 0, amount = 5000 },
        { name = 'weapon_bread',       price = 0, amount = 5000 },
        { name = 'weapon_stone_hatchet', price = 0, amount = 5000 },
        { name = 'weapon_candycane',   price = 0, amount = 5000 },
        { name = 'weapon_pistol_mk2',  price = 0, amount = 5000 },
        { name = 'weapon_combatpistol', price = 0, amount = 5000 },
        { name = 'weapon_appistol',    price = 0, amount = 5000 },
        { name = 'weapon_pistol50',    price = 0, amount = 5000 },
        { name = 'weapon_heavypistol', price = 0, amount = 5000 },
        { name = 'weapon_flaregun',    price = 0, amount = 5000 },
        { name = 'weapon_marksmanpistol', price = 0, amount = 5000 },
        { name = 'weapon_revolver',    price = 0, amount = 5000 },
        { name = 'weapon_revolver_mk2', price = 0, amount = 5000 },
        { name = 'weapon_doubleaction', price = 0, amount = 5000 },
        { name = 'weapon_snspistol_mk2', price = 0, amount = 5000 },
        { name = 'weapon_raypistol',   price = 0, amount = 5000 },
        { name = 'weapon_ceramicpistol', price = 0, amount = 5000 },
        { name = 'weapon_navyrevolver', price = 0, amount = 5000 },
        { name = 'weapon_gadgetpistol', price = 0, amount = 5000 },
        { name = 'weapon_pistolxm3',   price = 0, amount = 5000 },
        { name = 'weapon_microsmg',    price = 0, amount = 5000 },
        { name = 'weapon_smg',         price = 0, amount = 5000 },
        { name = 'weapon_smg_mk2',     price = 0, amount = 5000 },
        { name = 'weapon_assaultsmg',  price = 0, amount = 5000 },
        { name = 'weapon_combatpdw',   price = 0, amount = 5000 },
        { name = 'weapon_machinepistol', price = 0, amount = 5000 },
        { name = 'weapon_minismg',     price = 0, amount = 5000 },
        { name = 'weapon_raycarbine',  price = 0, amount = 5000 },       
		{ name = 'weapon_sniperrifle',          price = 0, amount = 5000 },
		{ name = 'weapon_assaultrifle',         price = 0, amount = 5000 },
		{ name = 'weapon_pumpshotgun',      price = 0, amount = 5000 },
        { name = 'weapon_sawnoffshotgun',   price = 0, amount = 5000 },
        { name = 'weapon_assaultshotgun',   price = 0, amount = 5000 },
        { name = 'weapon_bullpupshotgun',   price = 0, amount = 5000 },
        { name = 'weapon_musket',           price = 0, amount = 5000 },
        { name = 'weapon_heavyshotgun',     price = 0, amount = 5000 },
        { name = 'weapon_dbshotgun',        price = 0, amount = 5000 },
        { name = 'weapon_autoshotgun',      price = 0, amount = 5000 },
        { name = 'weapon_pumpshotgun_mk2',  price = 0, amount = 5000 },
        { name = 'weapon_combatshotgun',    price = 0, amount = 5000 },        
        { name = 'weapon_assaultrifle_mk2',     price = 0, amount = 5000 },
        { name = 'weapon_carbinerifle',         price = 0, amount = 5000 },
        { name = 'weapon_carbinerifle_mk2',     price = 0, amount = 5000 },
        { name = 'weapon_advancedrifle',        price = 0, amount = 5000 },
        { name = 'weapon_specialcarbine',       price = 0, amount = 5000 },
        { name = 'weapon_bullpuprifle',         price = 0, amount = 5000 },
        { name = 'weapon_compactrifle',         price = 0, amount = 5000 },
        { name = 'weapon_specialcarbine_mk2',   price = 0, amount = 5000 },
        { name = 'weapon_bullpuprifle_mk2',     price = 0, amount = 5000 },
        { name = 'weapon_militaryrifle',        price = 0, amount = 5000 },   
        { name = 'weapon_heavysniper',          price = 0, amount = 5000 },
        { name = 'weapon_marksmanrifle',        price = 0, amount = 5000 },
        { name = 'weapon_remotesniper',         price = 0, amount = 5000 },
        { name = 'weapon_heavysniper_mk2',      price = 0, amount = 5000 },
        { name = 'weapon_marksmanrifle_mk2',    price = 0, amount = 5000 },       
        { name = 'weapon_grenadelauncher',      price = 0, amount = 5000 },
        { name = 'weapon_grenadelauncher_smoke', price = 0, amount = 5000 },
        { name = 'weapon_minigun',              price = 0, amount = 5000 },
        { name = 'weapon_firework',             price = 0, amount = 5000 },
		{ name = 'weapon_grenade',              price = 0, amount = 5000 },
        { name = 'weapon_bzgas',                price = 0, amount = 5000 },
        { name = 'weapon_molotov',              price = 0, amount = 5000 },
        { name = 'weapon_stickybomb',           price = 0, amount = 5000 },
        { name = 'weapon_proxmine',             price = 0, amount = 5000 },
        { name = 'weapon_snowball',             price = 0, amount = 5000 },
        { name = 'weapon_pipebomb',             price = 0, amount = 5000 },
        { name = 'weapon_ball',                 price = 0, amount = 5000 },
        { name = 'weapon_smokegrenade',         price = 0, amount = 5000 },
        { name = 'weapon_flare',                price = 0, amount = 5000 },
		{ name = 'weapon_petrolcan',            price = 0, amount = 5000 },
        { name = 'weapon_fireextinguisher',     price = 0, amount = 5000 },
        { name = 'weapon_hazardcan',            price = 0, amount = 5000 },
		{ name = 'weapon_mg',                   price = 0, amount = 5000 },
        { name = 'weapon_combatmg',             price = 0, amount = 5000 },
        { name = 'weapon_gusenberg',            price = 0, amount = 5000 },
        { name = 'weapon_combatmg_mk2',         price = 0, amount = 5000 },
    },
	['ammo'] = {
        { name = 'mg_ammo',                     price = 0, amount = 5000 },
        { name = 'snp_ammo',                    price = 0, amount = 5000 },
		{ name = 'rifle_ammo',                  price = 0, amount = 5000 },
		{ name = 'shotgun_ammo',                price = 0, amount = 5000 },
		{ name = 'smg_ammo',                    price = 0, amount = 5000 },
		{ name = 'pistol_ammo',                 price = 0, amount = 5000 },
    },
    ['ambulance'] = {
        { name = 'bandage',             price = 0, amount = 5000 },
        { name = 'painkillers',         price = 0, amount = 5000 },
        { name = 'firstaid',            price = 0, amount = 5000 },
        { name = 'ifaks',               price = 0, amount = 5000 },
		{ name = 'narcan',               price = 0, amount = 5000 },
		{ name = 'detox_kit',               price = 0, amount = 5000 },
		{ name = 'test_kit',               price = 0, amount = 5000 },
    },
    ['attachment'] = {
        { name = 'clip_attachment',         price = 0, amount = 5000 },
        { name = 'drum_attachment',         price = 0, amount = 5000 },
        { name = 'flashlight_attachment',   price = 0, amount = 5000 },
        { name = 'suppressor_attachment',   price = 0, amount = 5000 },
        { name = 'smallscope_attachment',   price = 0, amount = 5000 },
        { name = 'medscope_attachment',     price = 0, amount = 5000 },
        { name = 'largescope_attachment',   price = 0, amount = 5000 },
        { name = 'holoscope_attachment',    price = 0, amount = 5000 },
        { name = 'advscope_attachment',     price = 0, amount = 5000 },
        { name = 'nvscope_attachment',      price = 0, amount = 5000 },
        { name = 'thermalscope_attachment', price = 0, amount = 5000 },
        { name = 'flat_muzzle_brake',       price = 0, amount = 5000 },
        { name = 'tactical_muzzle_brake',   price = 0, amount = 5000 },
        { name = 'fat_end_muzzle_brake',    price = 0, amount = 5000 },
        { name = 'precision_muzzle_brake',  price = 0, amount = 5000 },
        { name = 'heavy_duty_muzzle_brake', price = 0, amount = 5000 },
        { name = 'slanted_muzzle_brake',    price = 0, amount = 5000 },
        { name = 'split_end_muzzle_brake',  price = 0, amount = 5000 },
        { name = 'squared_muzzle_brake',    price = 0, amount = 5000 },
        { name = 'bellend_muzzle_brake',    price = 0, amount = 5000 },
        { name = 'barrel_attachment',       price = 0, amount = 5000 },
        { name = 'grip_attachment',         price = 0, amount = 5000 },
        { name = 'comp_attachment',         price = 0, amount = 5000 },
        { name = 'luxuryfinish_attachment', price = 0, amount = 5000 },
        { name = 'digicamo_attachment',     price = 0, amount = 5000 },
        { name = 'brushcamo_attachment',    price = 0, amount = 5000 },
        { name = 'woodcamo_attachment',     price = 0, amount = 5000 },
        { name = 'skullcamo_attachment',    price = 0, amount = 5000 },
        { name = 'sessantacamo_attachment', price = 0, amount = 5000 },
        { name = 'perseuscamo_attachment',  price = 0, amount = 5000 },
        { name = 'leopardcamo_attachment',  price = 0, amount = 5000 },
        { name = 'zebracamo_attachment',    price = 0, amount = 5000 },
        { name = 'geocamo_attachment',      price = 0, amount = 5000 },
        { name = 'boomcamo_attachment',     price = 0, amount = 5000 },
        { name = 'patriotcamo_attachment',  price = 0, amount = 5000 },
    },
    ['weapon tints'] = {
        { name = 'weapontint_0',            price = 0, amount = 5000 },
        { name = 'weapontint_1',            price = 0, amount = 5000 },
        { name = 'weapontint_2',            price = 0, amount = 5000 },
        { name = 'weapontint_3',            price = 0, amount = 5000 },
        { name = 'weapontint_4',            price = 0, amount = 5000 },
        { name = 'weapontint_5',            price = 0, amount = 5000 },
        { name = 'weapontint_6',            price = 0, amount = 5000 },
        { name = 'weapontint_7',            price = 0, amount = 5000 },
        { name = 'weapontint_mk2_0',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_1',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_2',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_3',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_4',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_5',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_6',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_7',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_8',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_9',        price = 0, amount = 5000 },
        { name = 'weapontint_mk2_10',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_11',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_12',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_13',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_14',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_15',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_16',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_17',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_18',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_19',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_20',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_21',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_22',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_23',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_24',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_25',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_26',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_27',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_28',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_29',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_30',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_31',       price = 0, amount = 5000 },
        { name = 'weapontint_mk2_32',       price = 0, amount = 5000 },
    },
    ['cards'] = {
        { name = 'id_card',                     price = 0, amount = 5000 },
        { name = 'driver_license',              price = 0, amount = 5000 },
        { name = 'weaponlicense',               price = 0, amount = 5000 },
        { name = 'bank_card',                   price = 0, amount = 5000 },
		{ name = 'specialbadge',                price = 0, amount = 5000 },
    },
    ['electronics'] = {
        { name = 'phone',                       price = 0, amount = 5000 },
        { name = 'radio',                       price = 0, amount = 5000 },
        { name = 'tablet',                      price = 0, amount = 5000 },
    },
    ['crafting'] = {
            { name = 'item_bench',                  price = 0, amount = 5000 },
            { name = 'attachment_bench',            price = 0, amount = 5000 },
        }
    },
}